packages:
  - '.'
  - '../../packages/const'
  - '../../packages/types'
  - '../../packages/utils'
  - '../../packages/model-bank'
  - '../../packages/web-crawler'
  - '../../packages/ssrf-safe-fetch'
